# This is the actual K8s Secret manifest with all secrets in one place
# For local testing only - in production use proper secret management
apiVersion: v1
kind: Secret
metadata:
  name: secrets
  labels:
    app.kubernetes.io/name: shared-secrets
    app.kubernetes.io/component: secrets
type: Opaque
stringData:
  # acme main db
  calls-db.yaml: |
    host: ssm://dev-rds-default/host
    port: ssm://dev-rds-default/port
    user: ssm://dev-rds-default/username
    password: ssm://dev-rds-default/password
    database: calls
  # Alternate db for testing only
  crm-db.yaml: |
    host: postgres
    port: 5432
    database: pipeline
    user: postgres
    password: postgres_password
  # Opensearch  config
  opensearch.yaml: |
    accessKeyId: ssm://dev-aws-es/access_id
    accessKeySecret: ssm://dev-aws-es/access_secret
    esHost: https://es.acmeqa.com
    esRegion: us-west-1
    tenantIsolationLevel: tenant  # tenant, crm, or none
  # Hubspot config
  hubspot.yaml: |
    hubspotClientId: ssm://shared-crm/hubspot_client_id
    hubspotClientSecret:  ssm://shared-crm/hubspot_client_secret
    hubspotLoginUri: https://app.hubspot.com/oauth/authorize
    hubspotRedirectUri: https://app.acme.com/oauth/hubspot-signup.php