apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
- service-nodeport.yaml
- configmap.yaml

labels:
- pairs:
    app: simple-publisher
    component: publisher
    tier: application

namespace: default
