apiVersion: v1
kind: Service
metadata:
  name: simple-publisher
  labels:
    app: simple-publisher
    component: publisher
    tier: application
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: simple-publisher
