# Intent subscriber configuration for sandbox
decisionUrl: https://api-blue.acmedev.com
intentTTLDays: 7
cacheType: 'in-memory'
cacheTableName: 'calls.intents'
cacheTtlSeconds: 3600
cacheHealthMaxAgeMinutes: 60
cacheInMemoryMaxSize: 1000
cacheTtlMaxStaleSeconds: 86400
cacheHealthCheckIntervalSeconds: 60
logLevel: "info"
