apiVersion: v1
kind: Service
metadata:
  name: webhook-subscriber
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: webhook-subscriber
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30080
      protocol: TCP
      name: http
