apiVersion: v1
kind: Service
metadata:
  name: datadog-agent-nodeport
  labels:
    app.kubernetes.io/name: datadog-agent
spec:
  selector:
    app.kubernetes.io/name: datadog-agent
  type: NodePort
  ports:
    - name: traces
      port: 8126
      targetPort: 8126
      protocol: TCP
      nodePort: 8126
    - name: dogstatsd
      port: 8125
      targetPort: 8125
      protocol: UDP
      nodePort: 8125
